[package]
name = "rust_lib_sudoku"
version = "0.1.0"
edition = "2021"
# resolver = "2"

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
flutter_rust_bridge = "=2.0.0-dev.32"
solver = {path = "../solver"}
lazy_static = "*"
rand = "*"
