// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.0.0-dev.24.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<String?> generateWithSize(
        {required int size, required List<String> rulesSrc, dynamic hint}) =>
    RustLib.instance.api
        .generateWithSize(size: size, rulesSrc: rulesSrc, hint: hint);

Future<int?> waitForProgess({dynamic hint}) =>
    RustLib.instance.api.waitForProgess(hint: hint);

Future<bool> checkLegality(
        {required int position, required int value, dynamic hint}) =>
    RustLib.instance.api
        .checkLegality(position: position, value: value, hint: hint);
